from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

import httpx


STATIC_COVER_GLOBAL = "__TRIANGULUM_STATIC_COVERS__"
STATIC_COVER_MANIFEST = Path("assets/cover-manifest.js")
STATIC_COVER_DIR = Path("assets/covers")
MAX_COVER_BYTES = 2_500_000


@dataclass(frozen=True)
class StaticCoverAssets:
    total_urls: int
    cache_hits: int
    fetched: int
    failed: int
    manifest_path: Path


def normalize_cover_url(value: str | None) -> str | None:
    """Return the browser-facing canonical form of a remote cover URL."""

    raw = (value or "").strip()
    if not raw:
        return None
    parsed = urlsplit(raw)
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc:
        return None
    return urlunsplit(("https", parsed.netloc, parsed.path, parsed.query, ""))


def _asset_key(url: str) -> str:
    return hashlib.sha256(url.encode("utf-8")).hexdigest()


def _image_suffix(content_type: str, content: bytes) -> str | None:
    media_type = content_type.split(";", 1)[0].strip().lower()
    by_type = {
        "image/jpeg": ".jpg",
        "image/jpg": ".jpg",
        "image/png": ".png",
        "image/webp": ".webp",
        "image/gif": ".gif",
        "image/avif": ".avif",
    }
    if media_type in by_type:
        return by_type[media_type]
    if content.startswith(b"\xff\xd8\xff"):
        return ".jpg"
    if content.startswith(b"\x89PNG\r\n\x1a\n"):
        return ".png"
    if content.startswith(b"GIF87a") or content.startswith(b"GIF89a"):
        return ".gif"
    if content.startswith(b"RIFF") and content[8:12] == b"WEBP":
        return ".webp"
    if len(content) >= 12 and content[4:8] == b"ftyp" and b"avif" in content[8:16]:
        return ".avif"
    return None


def _atomic_write_bytes(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f"{path.name}.tmp")
    temporary.write_bytes(content)
    temporary.replace(path)


def _atomic_write_text(path: Path, content: str) -> None:
    _atomic_write_bytes(path, content.encode("utf-8"))


def _cover_urls_from_payload(payload: Any) -> set[str]:
    urls: set[str] = set()

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            cover = value.get("cover")
            if isinstance(cover, dict) and cover.get("has_cover") is True:
                normalized = normalize_cover_url(cover.get("optimized_cover_url"))
                if normalized:
                    urls.add(normalized)
            for child in value.values():
                walk(child)
        elif isinstance(value, list):
            for child in value:
                walk(child)

    walk(payload)
    return urls


def _published_cover_urls(data_dir: Path) -> list[str]:
    urls: set[str] = set()
    if not data_dir.exists():
        return []
    for path in sorted(data_dir.rglob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        urls.update(_cover_urls_from_payload(payload))
    return sorted(urls)


def _cached_cover(cache_dir: Path, key: str) -> tuple[Path, str] | None:
    metadata_path = cache_dir / f"{key}.json"
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    filename = metadata.get("filename") if isinstance(metadata, dict) else None
    if not isinstance(filename, str) or not filename.startswith(f"{key}."):
        return None
    candidate = cache_dir / filename
    if not candidate.is_file() or candidate.stat().st_size <= 0:
        return None
    return candidate, filename


def _write_manifest(path: Path, mapping: dict[str, str]) -> None:
    serialized = json.dumps(dict(sorted(mapping.items())), ensure_ascii=False, separators=(",", ":"))
    serialized = serialized.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    _atomic_write_text(
        path,
        "// Generated by daily3albums build. Do not edit.\n"
        f"window.{STATIC_COVER_GLOBAL} = Object.freeze({serialized});\n",
    )


def materialize_static_cover_assets(
    out_public_dir: Path,
    *,
    cache_dir: Path,
    client: httpx.Client | None = None,
    timeout_s: float = 12.0,
    max_bytes: int = MAX_COVER_BYTES,
) -> StaticCoverAssets:
    """Fetch published remote cover art once during build and write a local map.

    The public issue and archive JSON remain byte-for-byte untouched. The UI maps
    their existing remote cover URLs to these Pages-hosted files at render time.
    Failed fetches are deliberately omitted from the map so the established image
    fallback path still applies without weakening archive safety.
    """

    urls = _published_cover_urls(out_public_dir / "data")
    cache_dir.mkdir(parents=True, exist_ok=True)
    output_dir = out_public_dir / STATIC_COVER_DIR
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    owns_client = client is None
    if client is None:
        client = httpx.Client(
            follow_redirects=True,
            timeout=httpx.Timeout(timeout_s),
            headers={"User-Agent": "TriangulumDailyCoverCache/1.0"},
        )

    mapping: dict[str, str] = {}
    cache_hits = 0
    fetched = 0
    failed = 0
    try:
        for url in urls:
            key = _asset_key(url)
            cached = _cached_cover(cache_dir, key)
            if cached is None:
                try:
                    response = client.get(url)
                    response.raise_for_status()
                    content = response.content
                    if not content or len(content) > max_bytes:
                        raise ValueError("cover payload is empty or exceeds the size limit")
                    suffix = _image_suffix(response.headers.get("content-type", ""), content)
                    if suffix is None:
                        raise ValueError("cover payload is not a supported raster image")
                    filename = f"{key}{suffix}"
                    cached_path = cache_dir / filename
                    _atomic_write_bytes(cached_path, content)
                    _atomic_write_text(
                        cache_dir / f"{key}.json",
                        json.dumps({"filename": filename, "source_url": url}, ensure_ascii=False) + "\n",
                    )
                    cached = (cached_path, filename)
                    fetched += 1
                except (httpx.HTTPError, OSError, ValueError):
                    failed += 1
                    continue
            else:
                cache_hits += 1

            cached_path, filename = cached
            output_path = output_dir / filename
            shutil.copy2(cached_path, output_path)
            mapping[url] = (STATIC_COVER_DIR / filename).as_posix()
    finally:
        if owns_client:
            client.close()

    manifest_path = out_public_dir / STATIC_COVER_MANIFEST
    _write_manifest(manifest_path, mapping)
    return StaticCoverAssets(
        total_urls=len(urls),
        cache_hits=cache_hits,
        fetched=fetched,
        failed=failed,
        manifest_path=manifest_path,
    )
